//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/scripts/Input/OnePlayerInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @OnePlayerInputs: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @OnePlayerInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""OnePlayerInputs"",
    ""maps"": [
        {
            ""name"": ""OnePlayer"",
            ""id"": ""7359818d-d879-4561-ae25-c85dc0adc336"",
            ""actions"": [
                {
                    ""name"": ""LeftJoystick"",
                    ""type"": ""Value"",
                    ""id"": ""cefe38d1-e091-4846-b67e-87c90b0ec391"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightJoystick"",
                    ""type"": ""Value"",
                    ""id"": ""ad0b249b-3a75-4f12-8e20-f58561fc3038"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""HoldLeft"",
                    ""type"": ""Button"",
                    ""id"": ""c3bed0b9-a2c9-47dd-8f39-5cadef9b9b0f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HoldRight"",
                    ""type"": ""Button"",
                    ""id"": ""32a8d9ba-1373-4ad6-8356-2896acc4c5a0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OptionsOpen"",
                    ""type"": ""Button"",
                    ""id"": ""88e61085-ab0f-48ed-829e-6f8c205f4c76"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Movewherever"",
                    ""type"": ""Button"",
                    ""id"": ""d3292ceb-c08b-4d1f-b540-cd2ae1116e4c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Back"",
                    ""type"": ""Button"",
                    ""id"": ""19aacbd6-e5d6-4581-9eff-e1ec0fcdb0aa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7e9c8ca1-a972-4495-92ee-c84267aab44a"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftJoystick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""ee0e5d95-b586-4b5d-97e4-a55375e646ca"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftJoystick"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""9cac509f-ca62-411c-8066-2349665de94f"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftJoystick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""dad8efa6-7ed1-4c6a-957d-b7bf5ca78551"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftJoystick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""ab19fe6a-b97d-4c16-8cdb-4b75fc9b25af"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftJoystick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""af15006e-98ef-4981-8b76-744d9b3ebef0"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftJoystick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""a0d4285a-9411-4e95-898b-2e7f2ef16361"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightJoystick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""bf105e14-7a13-4c83-934b-e0747d7c3b3f"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightJoystick"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""2e1754b2-de4e-48a4-ae49-9bc40b39f03c"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightJoystick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""d367346d-3a76-4c8c-b0dd-ff478c05b8d5"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightJoystick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""0afedacc-9579-4620-a9eb-581b63b86e8d"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightJoystick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""c0ccded0-b126-414a-8034-030a031dc1e3"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightJoystick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""3b71a29e-6077-441a-9767-0c8baec5863e"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HoldLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""64807d7f-1510-4335-8286-b33c65f042e9"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HoldLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d2737328-daee-4709-abc8-24e9ee5a8773"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HoldLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""073d3b81-f896-4321-9316-ad3f6cfa4762"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HoldRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b2de7fb9-72de-4502-aaa8-af9ca559aca5"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HoldRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""80275bf8-648f-4245-af32-0c5eea62ae48"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HoldRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e05d30b6-9ebb-4a19-ae68-3f99d8c01e50"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OptionsOpen"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7473afce-d75d-4339-9480-b32131b95e7f"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OptionsOpen"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2a277673-d742-4443-974c-521dc1dc5c32"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movewherever"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""db229ec9-e669-46f5-b74c-eb86ce718197"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // OnePlayer
        m_OnePlayer = asset.FindActionMap("OnePlayer", throwIfNotFound: true);
        m_OnePlayer_LeftJoystick = m_OnePlayer.FindAction("LeftJoystick", throwIfNotFound: true);
        m_OnePlayer_RightJoystick = m_OnePlayer.FindAction("RightJoystick", throwIfNotFound: true);
        m_OnePlayer_HoldLeft = m_OnePlayer.FindAction("HoldLeft", throwIfNotFound: true);
        m_OnePlayer_HoldRight = m_OnePlayer.FindAction("HoldRight", throwIfNotFound: true);
        m_OnePlayer_OptionsOpen = m_OnePlayer.FindAction("OptionsOpen", throwIfNotFound: true);
        m_OnePlayer_Movewherever = m_OnePlayer.FindAction("Movewherever", throwIfNotFound: true);
        m_OnePlayer_Back = m_OnePlayer.FindAction("Back", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // OnePlayer
    private readonly InputActionMap m_OnePlayer;
    private List<IOnePlayerActions> m_OnePlayerActionsCallbackInterfaces = new List<IOnePlayerActions>();
    private readonly InputAction m_OnePlayer_LeftJoystick;
    private readonly InputAction m_OnePlayer_RightJoystick;
    private readonly InputAction m_OnePlayer_HoldLeft;
    private readonly InputAction m_OnePlayer_HoldRight;
    private readonly InputAction m_OnePlayer_OptionsOpen;
    private readonly InputAction m_OnePlayer_Movewherever;
    private readonly InputAction m_OnePlayer_Back;
    public struct OnePlayerActions
    {
        private @OnePlayerInputs m_Wrapper;
        public OnePlayerActions(@OnePlayerInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @LeftJoystick => m_Wrapper.m_OnePlayer_LeftJoystick;
        public InputAction @RightJoystick => m_Wrapper.m_OnePlayer_RightJoystick;
        public InputAction @HoldLeft => m_Wrapper.m_OnePlayer_HoldLeft;
        public InputAction @HoldRight => m_Wrapper.m_OnePlayer_HoldRight;
        public InputAction @OptionsOpen => m_Wrapper.m_OnePlayer_OptionsOpen;
        public InputAction @Movewherever => m_Wrapper.m_OnePlayer_Movewherever;
        public InputAction @Back => m_Wrapper.m_OnePlayer_Back;
        public InputActionMap Get() { return m_Wrapper.m_OnePlayer; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(OnePlayerActions set) { return set.Get(); }
        public void AddCallbacks(IOnePlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_OnePlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_OnePlayerActionsCallbackInterfaces.Add(instance);
            @LeftJoystick.started += instance.OnLeftJoystick;
            @LeftJoystick.performed += instance.OnLeftJoystick;
            @LeftJoystick.canceled += instance.OnLeftJoystick;
            @RightJoystick.started += instance.OnRightJoystick;
            @RightJoystick.performed += instance.OnRightJoystick;
            @RightJoystick.canceled += instance.OnRightJoystick;
            @HoldLeft.started += instance.OnHoldLeft;
            @HoldLeft.performed += instance.OnHoldLeft;
            @HoldLeft.canceled += instance.OnHoldLeft;
            @HoldRight.started += instance.OnHoldRight;
            @HoldRight.performed += instance.OnHoldRight;
            @HoldRight.canceled += instance.OnHoldRight;
            @OptionsOpen.started += instance.OnOptionsOpen;
            @OptionsOpen.performed += instance.OnOptionsOpen;
            @OptionsOpen.canceled += instance.OnOptionsOpen;
            @Movewherever.started += instance.OnMovewherever;
            @Movewherever.performed += instance.OnMovewherever;
            @Movewherever.canceled += instance.OnMovewherever;
            @Back.started += instance.OnBack;
            @Back.performed += instance.OnBack;
            @Back.canceled += instance.OnBack;
        }

        private void UnregisterCallbacks(IOnePlayerActions instance)
        {
            @LeftJoystick.started -= instance.OnLeftJoystick;
            @LeftJoystick.performed -= instance.OnLeftJoystick;
            @LeftJoystick.canceled -= instance.OnLeftJoystick;
            @RightJoystick.started -= instance.OnRightJoystick;
            @RightJoystick.performed -= instance.OnRightJoystick;
            @RightJoystick.canceled -= instance.OnRightJoystick;
            @HoldLeft.started -= instance.OnHoldLeft;
            @HoldLeft.performed -= instance.OnHoldLeft;
            @HoldLeft.canceled -= instance.OnHoldLeft;
            @HoldRight.started -= instance.OnHoldRight;
            @HoldRight.performed -= instance.OnHoldRight;
            @HoldRight.canceled -= instance.OnHoldRight;
            @OptionsOpen.started -= instance.OnOptionsOpen;
            @OptionsOpen.performed -= instance.OnOptionsOpen;
            @OptionsOpen.canceled -= instance.OnOptionsOpen;
            @Movewherever.started -= instance.OnMovewherever;
            @Movewherever.performed -= instance.OnMovewherever;
            @Movewherever.canceled -= instance.OnMovewherever;
            @Back.started -= instance.OnBack;
            @Back.performed -= instance.OnBack;
            @Back.canceled -= instance.OnBack;
        }

        public void RemoveCallbacks(IOnePlayerActions instance)
        {
            if (m_Wrapper.m_OnePlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IOnePlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_OnePlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_OnePlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public OnePlayerActions @OnePlayer => new OnePlayerActions(this);
    public interface IOnePlayerActions
    {
        void OnLeftJoystick(InputAction.CallbackContext context);
        void OnRightJoystick(InputAction.CallbackContext context);
        void OnHoldLeft(InputAction.CallbackContext context);
        void OnHoldRight(InputAction.CallbackContext context);
        void OnOptionsOpen(InputAction.CallbackContext context);
        void OnMovewherever(InputAction.CallbackContext context);
        void OnBack(InputAction.CallbackContext context);
    }
}
